# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e9879fd5fcf5da232c9baecaec39a4a9756b5005e6ac59dd1f8ebdba70ecc38de5001d46fd1e63f29389110af79b7155096f76406a69ae935348194a61ba4b6

test:
  secret_key_base: 51da56f64575b7b6a309a430155f3db48ed7e8d119fc17142b0175f69a1c058a140c967a02cdd3760b78ef388494d85a2cfe34b2fec03e7b3b79fe1aee9a5400

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
